#! /usr/bin/env bash

# Run this as sudo -i nix-install-deb-multi-user
# see https://nixos.wiki/wiki/Install_Nix_in_multi-user_mode_on_non-NixOS

set -e

echo "performing a multi-user installation of Nix..." >&2

tmpDir="$(mktemp -d -t nix-binary-tarball-unpack.XXXXXXXXXX || \
          oops "Can\'t create temporary directory for downloading the Nix tarball")"
cleanup() {
    rm -rf "$tmpDir"
}
trap cleanup EXIT INT QUIT TERM

apt-get update
apt-get install wget curl build-essential \
	pkg-config autotools-dev dh-autoreconf libssl-dev libbz2-dev \
	libsqlite3-dev libcurl4-openssl-dev liblzma-dev libgc-dev \
	libdbi-perl libdbd-sqlite3-perl libwww-curl-perl libxml2 libxslt-dev \
	systemd;

groupadd -r nixbld
for n in $(seq 1 10); do useradd -c "Nix build user $n" \
    -d /var/empty -g nixbld -G nixbld -M -N -r -s "$(which nologin)" \
    nixbld$n; done

wget "https://nixos.org/releases/nix/nix-1.11.2/nix-1.11.2.tar.xz" -P $tmpDir
tar -xvf nix-1.11.2.tar.xz
cd $tempDir"/nix-1.11.2/"
./configure --enable-gc
make -j $(cat /proc/cpuinfo | awk '/^processor/{print $3}' | tail -1)
make install

touch "/etc/systemd/system/nix.service";
$(cat >> "/etc/systemd/system/nix.service" <<'END_HEREDOC'
[Unit]
Description=Nix daemon

[Service]
EnvironmentFile=-/etc/default/nix
ExecStart=/usr/local/bin/nix-daemon $EXTRA_OPTS
IgnoreSIGPIPE=false
KillMode=process

[Install]
WantedBy=multi-user.target
END_HEREDOC
)

touch /etc/default/nix

systemctl enable nix
systemctl start nix

# TODO should this be put into .bash_profile, as above?
touch "/root/.bashrc"
$(cat >> "/root/.bashrc" <<'END_HEREDOC'

nix-setup-user() {
        TARGET_USER="$1"
        SYMLINK_PATH="/home/$TARGET_USER/.nix-profile"
        PROFILE_DIR="/nix/var/nix/profiles/per-user/$TARGET_USER"

        echo "Creating profile $PROFILE_DIR..."
        echo "Profile symlink: $SYMLINK_PATH"

        rm "$SYMLINK_PATH"
        mkdir -p "$PROFILE_DIR"
        chown "$TARGET_USER" "$PROFILE_DIR"
        
        ln -s "$PROFILE_DIR/profile" "$SYMLINK_PATH"
        chown -h "$TARGET_USER" "$SYMLINK_PATH"
        
        echo "export NIX_REMOTE=daemon" >> "/home/$TARGET_USER/.bashrc"
        echo ". /usr/local/etc/profile.d/nix.sh" >> "/home/$TARGET_USER/.bashrc"
        
        su -lc "cd; . /usr/local/etc/profile.d/nix.sh; NIX_REMOTE=daemon nix-channel --update" "$TARGET_USER"
}
END_HEREDOC
)

echo "To setup nix for a user, e.g., jdoe, run 'sudo -i nix-setup-user jdoe'"
